### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by akerl** [shawnrice/alfred-2-caffeinate-workflow#13]
Howdy!

I'm a big fan of this workflow, and as part of some automation I'm looking to add it as a submodule to one of my own repos.

I noticed there's not a license file or note in the repo; would it be possible to add one?

**Comment by shawnrice** [comment]
Glad you like it. I'll add one this weekend. It'll be MIT. That should be permissible enough, correct?

**Comment by akerl** [comment]
MIT is awesome; thanks!

**Comment by shawnrice** [comment]
#14 closes this.
