### ISSUE TITLE
not working on alfred 4

### ISSUE THREAD

**Issue by nailuoGG** [shawnrice/alfred-2-caffeinate-workflow#16]
I Think this cause by:

VPREFS="$HOME/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/"
NVPREFS="$HOME/Library/Application Support/Alfred 2/Workflow Data/"

by  change NVPREFS variable:

NVPREFS="$HOME/Library/Application Support/Alfred 2/Workflow Data/"

It works!

**Comment by ImJoeHs** [comment]
it should be 
```
NVPREFS="$HOME/Library/Application Support/Alfred/Workflow Data/"
```

Alfred 2 => Alfred

**Comment by wwwfeng** [comment]
it works
