### ISSUE TITLE
Enabling with no timeout, i.e. forever, shows "Caffeinate will be active for another "

### ISSUE THREAD

**Issue by tupton** [shawnrice/alfred-2-caffeinate-workflow#6]
It looks like the check for whether caffeinate is running forever doesn't always work. For me, in `script.sh` on line 35, `$total` is 0, not empty.

``` sh
if [[ -z "$total" ]]; then
```

The check should be something like

``` sh
if [[ -z "$total" || "$total" == 0 ]]; then
```

**Comment by tupton** [comment]
It looks like this is an issue with the [version posted at packal][0] but not with master here. Is there any way you can update that version to the latest?

  [0]: http://www.packal.org/workflow/caffeinate-control

(Also, not quite as important, but it'd be super-awesome to use tags and github's releases to track different versions)

**Comment by shawnrice** [comment]
Yeah. I should do both of those.
