### ISSUE TITLE
Typing 30 1 gives 1hour 30 minutes

### ISSUE THREAD

**Issue by danielnolan** [shawnrice/alfred-2-caffeinate-workflow#7]
If I type `30 1` in the alfred text box I get this
<img width="573" alt="screen shot 2016-05-03 at 9 38 47 am" src="https://cloud.githubusercontent.com/assets/635285/14984896/0e4bc9e4-1113-11e6-8698-78dc24a1d825.png">

I thought it was supposed to interpret the first number as hours and the second as minutes?

**Comment by wassimk** [comment]
Probably if two numbers exist it should assume hours and minutes but it does opposite. I did PR #8 to reflect that in the documentation. We should update the workflow for hours first.

**Comment by shawnrice** [comment]
This should be fixed now.
